version: 1
title: "Tutorial: Your First Code Review"
repository: starbase-app/starbase-tutorial

commits:
  initial: "d92871e"
  rework: "43ffd09"

steps:
  - id: step_1
    order: 1
    instruction: "Click the 'Start Reviewing' button to begin your code review."
    hint: "The 'Start Reviewing' button is in the action bar at the top of the review."
    expectedAction:
      type: start_reviewing
    botResponse:
      type: none

  - id: step_2
    order: 2
    instruction: "Click on the calculator.py cell in the file matrix to view the changes."
    hint: "The file matrix shows which files were changed in each commit. Click the cell at the intersection of the commit and calculator.py."
    expectedAction:
      type: select_cell
      filePath: "src/calculator.py"
    botResponse:
      type: none

  - id: step_3
    order: 3
    instruction: "Add a comment on line 5 of src/calculator.py noting the missing zero-division check."
    hint: "Use the annotation toolbar to add a comment. Comments are for general feedback that don't require changes."
    expectedAction:
      type: annotation
      annotationType: comment
      filePath: "src/calculator.py"
    botResponse:
      type: reply
      replyBody: "Thanks for the feedback! I'll keep that in mind."
      delay: 2000

  - id: step_4
    order: 4
    instruction: "Add a defect on line 4 of src/utils.py for the off-by-one error in range_sum."
    hint: "Defects are issues that must be addressed before the code can be approved."
    expectedAction:
      type: annotation
      annotationType: defect
      filePath: "src/utils.py"
    botResponse:
      type: reply
      replyBody: "Good catch! I'll fix that in the next commit."
      delay: 2000

  - id: step_5
    order: 5
    instruction: "Request changes from the author. Open the action menu and select 'Request Changes'."
    hint: "Click the dropdown arrow next to the action button and select 'Request Changes' to send the review back to the author."
    expectedAction:
      type: request_changes
    botResponse:
      type: none

  - id: step_6
    order: 6
    instruction: "The author has submitted a rework commit. Click on the new commit in the matrix to review the changes."
    hint: "A new column has appeared in the file matrix for the rework commit. Click on it to see what changed."
    expectedAction:
      type: select_commit
    botResponse:
      type: none

  - id: step_7
    order: 7
    instruction: "Click 'Start Reviewing' to resume your review of the rework commit."
    hint: "After rework is submitted, you need to start reviewing again before you can approve."
    expectedAction:
      type: start_reviewing
    botResponse:
      type: none

  - id: step_8
    order: 8
    instruction: "The changes look good! Approve the review by clicking the 'Approve' button."
    hint: "Click the 'Approve' button in the action bar to complete your review."
    expectedAction:
      type: approve
    botResponse:
      type: none
